name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: 1. git checkout...

      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: 2. setup hugo...

      uses: peaceiris/actions-hugo@v2
      with:
        extended: true
        hugo-version: '0.78.2'

    - name: 3. build...
      run: hugo --minify -D
    
    # 提交到我们的存放静态资源的仓库

    - name: 4. deploy...
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./public
        publish_branch: master